MIN_SLIDER_VALUE: int = 1
MAX_SLIDER_VALUE: int = 100
SLIDER_STEP: int = 1
SLIDER_STARTING_VALUE: int = 50

WINDOW_X_START: int = 500
WINDOW_Y_START: int = 50
WINDOW_WIDTH: int = 800
WINDOW_HEIGHT: int = 700

PLOT_PLACE_FROM_CANVAS: int = 111

ZOOM_IN: float = 0.8
ZOOM_OUT: float = 1 / ZOOM_IN