name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        qt-lib: [pyqt6, pyside6]
        os: [windows-latest, macos-latest]
        include:
          - python-version: "3.7"
            tox-env: "py37"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt
      - name: Set up app module
        run: |
          python -m pip install -e ./src/app/
      - name: Test with pytest
        run: |
          python -m pytest ./tests
